/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xpoly.ui.QLSach;

import com.xpoly.DAO.QuyenSachDAO;
import com.xpoly.DAO.TuaSachDAO;
import com.xpoly.Interface.IService;
import com.xpoly.model.QuyenSach;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class ChiTietSachJFrame extends javax.swing.JFrame implements IService<QuyenSach> {

    //    private int maQuyenSach;
//    private String viTri;
//    private boolean duocMuonVe;
//    private int tinhTrang;
//    private int trangThai;
//    private String ghiChu;
//    int maTuaSach;
//    duocmuonve bit not null, -- (duocmuonve = 1, doctaicho = 0)
//tinhtrang int default 0 not null, -- (dangphucvu = 0, hong = 1, mat = 2, ngungphucvu = 3)
//trangthai int default 0  not null, -- (sansanchomuon = 0, dangmuon = 1, duocdat = 2 )
    int maTuaSach;
    int rowIndex = 0;
    
    DefaultTableModel tblModel = new DefaultTableModel(new String[]{"Mã", "Vị trí", "Được mượn về", "Tình trạng", "Trạng thái", "Ghi chú"}, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            //all cells false
            return false;
        }
    };

    public ChiTietSachJFrame(int maTuaSach) {
        initComponents();
        this.maTuaSach = maTuaSach;
        System.out.println(maTuaSach);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_qSach = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_quit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_vitri = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ghiChu = new javax.swing.JTextArea();
        chk_duocmuonve = new javax.swing.JCheckBox();
        rdo_phucvu = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rdo_ngungphucvu = new javax.swing.JRadioButton();
        rdo_mat = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        lbl_tuaSach = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_qSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_qSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_qSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_qSach);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CHI TIẾT SÁCH ");

        btn_quit.setText("Exit");

        jLabel2.setText("Vị trí:");

        jLabel3.setText("Ghi chú");

        txt_ghiChu.setColumns(20);
        txt_ghiChu.setRows(5);
        jScrollPane2.setViewportView(txt_ghiChu);

        chk_duocmuonve.setText("Được mượn về");

        buttonGroup1.add(rdo_phucvu);
        rdo_phucvu.setSelected(true);
        rdo_phucvu.setText("Phục vụ");

        jLabel4.setText("Tình trạng");

        buttonGroup1.add(rdo_ngungphucvu);
        rdo_ngungphucvu.setText("Ngừng phục vụ");

        buttonGroup1.add(rdo_mat);
        rdo_mat.setText("Mất");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_vitri, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chk_duocmuonve)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdo_phucvu)
                                    .addComponent(rdo_mat))
                                .addGap(18, 18, 18)
                                .addComponent(rdo_ngungphucvu)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_vitri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chk_duocmuonve))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_phucvu)
                    .addComponent(jLabel4)
                    .addComponent(rdo_ngungphucvu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(rdo_mat)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lbl_tuaSach.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_quit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbl_tuaSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tuaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_quit)
                            .addComponent(jButton3)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_qSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_qSachMouseClicked
        // TODO add your handling code here:
        rowIndex = tbl_qSach.getSelectedRow();
        setModel(lst_quyenSach.get(rowIndex));
    }//GEN-LAST:event_tbl_qSachMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ChiTietSachJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_quit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chk_duocmuonve;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_tuaSach;
    private javax.swing.JRadioButton rdo_mat;
    private javax.swing.JRadioButton rdo_ngungphucvu;
    private javax.swing.JRadioButton rdo_phucvu;
    private javax.swing.JTable tbl_qSach;
    private javax.swing.JTextArea txt_ghiChu;
    private javax.swing.JTextField txt_vitri;
    // End of variables declaration//GEN-END:variables

    public void init() {
        lbl_tuaSach.setText(maTuaSach + " : " + new TuaSachDAO().selectById(maTuaSach).getTenTuaSach());
        tbl_qSach.setModel(tblModel);
        loadTable();
    }
    
    QuyenSachDAO quyenSachDAO = new QuyenSachDAO();
    QuyenSach quyenSach;
    List<QuyenSach> lst_quyenSach = new ArrayList<>();
    
    public void loadTable() {
        tblModel.setRowCount(0);
        try {
            lst_quyenSach = quyenSachDAO.selectAllByMaTuaSach(maTuaSach);
            for (QuyenSach x : lst_quyenSach) {
                tblModel.addRow(new Object[]{x.getMaQuyenSach(), x.getViTri(), x.isDuocMuonVe() ? "Được mượn về" : "Đọc tại chỗ", 
                    setTinhTrang(x.getTinhTrang()), setTrangThai(x.getTrangThai()), x.getGhiChu()});
            }
        } catch (Exception e) {
        }
    }
    
    @Override
    public void insert() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
    }
    
    @Override
    public void update() {
        quyenSachDAO.update(getModel());
        loadTable();
    }
    
    @Override
    public void delete() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    @Override
    public void clear() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    @Override
    public StringBuilder validateForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    @Override
    public QuyenSach getModel() {
        int maQuyenSach = lst_quyenSach.get(rowIndex).getMaQuyenSach();
        String vitri = txt_vitri.getText();
        String ghiChu = txt_ghiChu.getText();
        boolean duocMuonVe = chk_duocmuonve.isSelected();
        int tinhTrang = rdo_phucvu.isSelected() ? 0 : rdo_mat.isSelected() ? 2 : 3;
        int trangThai = lst_quyenSach.get(rowIndex).getTrangThai();
        if(tinhTrang != 0 && trangThai != 1){            
                trangThai = 3;
        }
        return new QuyenSach(maQuyenSach,vitri, duocMuonVe, tinhTrang, trangThai, ghiChu);
    }
    
    @Override
    public void setModel(QuyenSach model) {
        int trangThai = lst_quyenSach.get(rowIndex).getTrangThai();
        txt_vitri.setText(model.getViTri() == null ? "" : model.getViTri());
        txt_ghiChu.setText(model.getGhiChu());
        setrdoTinhTrang(model.getTinhTrang());
        chk_duocmuonve.setSelected(model.isDuocMuonVe());
    }
    
    private void setrdoTinhTrang(int tinhTrang){
        if(tinhTrang == 0){
            rdo_phucvu.isSelected();
        }
        else if (tinhTrang == 1){
            rdo_mat.isSelected();
        }
        else rdo_ngungphucvu.isSelected();
    }
    
        
    private String setTinhTrang(int tinhTrang){
        switch(tinhTrang){
            case 0: return "Đang phục vụ";
            case 1: return "Hỏng";
            case 2: return "Mất";
            case 3: return "Ngừng phục vụ";
        }
        return null;
    }
    
    private String setTrangThai(int tinhTrang){
        switch(tinhTrang){
            case 0: return "Sẵn sàng cho mượn";
            case 1: return "Đang mượn";
            case 2: return "Được đặt";
            case 3: return "Ngừng phục vụ";
        }
        return null;
    }
//tinhtrang int default 0 not null, -- (dangphucvu = 0, hong = 1, mat = 2, ngungphucvu = 3)
//trangthai int default 0  not null, -- (sansanchomuon = 0, dangmuon = 1, duocdat = 2 )
}
